(() => {
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); let profiles=[];
  const style=document.createElement('style');style.textContent=`.profile-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}.profile-card{position:relative}.profile-card.default{border-color:#9bb4f5}.profile-badges{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.profile-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.profile-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;z-index:100;padding:18px}.profile-modal.open{display:flex}.profile-dialog{background:#fff;border-radius:16px;max-width:900px;width:100%;max-height:92vh;overflow:auto;padding:22px;box-shadow:0 18px 60px rgba(0,0,0,.25)}.profile-dialog textarea{min-height:170px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.profile-checks{display:flex;gap:18px;flex-wrap:wrap;margin-top:10px}`;document.head.appendChild(style);

  function install(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('profiles'))return;const b=document.createElement('button');b.dataset.tab='profiles';b.textContent='Profiles';nav.insertBefore(b,nav.querySelector('[data-tab="search"]')||null);const s=document.createElement('section');s.id='profiles';s.className='section';s.innerHTML=`<div class="section-title"><div><h2>Search Profiles</h2><div class="hint">Each profile has independent scoring, language thresholds and learned preferences.</div></div><button class="btn primary" onclick="openProfileEditor()">New profile</button></div><div id="profileGrid" class="profile-grid"></div>`;main.appendChild(s);b.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Profiles';loadProfiles()});
    const modal=document.createElement('div');modal.id='profileModal';modal.className='profile-modal';modal.innerHTML=`<div class="profile-dialog"><div class="section-title" style="margin-top:0"><h2 id="profileModalTitle">Search profile</h2><button class="btn" onclick="closeProfileEditor()">Close</button></div><input type="hidden" id="pfId"><div class="form-grid">
      <div class="field"><label>Name</label><input id="pfName"></div><div class="field"><label>Slug</label><input id="pfSlug"></div>
      <div class="field"><label>Primary location</label><input id="pfLocation" value="Berlin"></div><div class="field"><label>Location terms</label><input id="pfLocations" placeholder="berlin,potsdam,hennigsdorf"></div>
      <div class="field"><label>Minimum Overall Fit</label><input id="pfMin" type="number" min="0" max="100"></div><div class="field"><label>Minimum Language Fit</label><input id="pfLangMin" type="number" min="0" max="100"></div>
      <div class="field"><label>Language weight %</label><input id="pfLangWeight" type="number" min="0" max="100"></div><div class="field"><label>Current German</label><select id="pfGerman"><option value="a2">A2</option><option value="a2_b1">A2 → B1</option><option value="b1">B1</option></select></div>
      <div class="field"><label>Maximum preferred German</label><select id="pfGermanMax"><option value="a2">A2</option><option value="b1">B1</option><option value="b2">B2</option></select></div>
      <div class="field full"><label>Scoring & search keywords (JSON)</label><textarea id="pfKeywords"></textarea><div class="hint">Sections: search, title, format, skill, negative. Values are score weights.</div></div>
    </div><div class="profile-checks"><label><input type="checkbox" id="pfEnabled"> Enabled</label><label><input type="checkbox" id="pfDefault"> Default profile</label><label><input type="checkbox" id="pfStretch"> Show B2 stretch</label><label><input type="checkbox" id="pfHideHeavy"> Hide German-heavy</label><label><input type="checkbox" id="pfGrowth"> Prefer German-growth</label></div><div class="actions"><button class="btn primary" onclick="saveProfileEditor()">Save profile</button><span id="profileSaveStatus" class="status"></span></div></div>`;document.body.appendChild(modal);
  }

  window.loadProfiles=async function(){const d=await api('/api/profiles');profiles=d.profiles;const grid=$('profileGrid');if(grid)grid.innerHTML=profiles.map(p=>`<div class="card profile-card ${p.is_default?'default':''}"><div class="source-title">${esc(p.name)}</div><div class="profile-badges"><span class="pill">${p.enabled?'Enabled':'Disabled'}</span>${p.is_default?'<span class="pill">Default</span>':''}<span class="pill">${esc(p.current_german_level.replace('_',' → ').toUpperCase())}</span></div><div class="muted">${esc(p.target_location)} · min ${p.min_score} · language min ${p.min_language_score} · language weight ${p.language_weight}%</div><div class="hint" style="margin-top:8px">${Object.keys(p.keywords?.search||{}).length} search phrases · ${Object.keys(p.keywords?.title||{}).length} title rules · ${Object.keys(p.keywords?.skill||{}).length} skill rules</div><div class="profile-actions"><button class="btn" onclick="openProfileEditor(${p.id})">Edit</button><button class="btn" onclick="activateProfile(${p.id})">Use in review</button>${p.is_default?'':`<button class="btn danger" onclick="removeProfile(${p.id})">Delete</button>`}</div></div>`).join('');return profiles};

  window.openProfileEditor=function(id){const p=id?profiles.find(x=>x.id===id):null;$('pfId').value=p?.id||'';$('profileModalTitle').textContent=p?'Edit search profile':'New search profile';$('pfName').value=p?.name||'';$('pfSlug').value=p?.slug||'';$('pfLocation').value=p?.target_location||'Berlin';$('pfLocations').value=(p?.location_terms||['berlin']).join(',');$('pfMin').value=p?.min_score??35;$('pfLangMin').value=p?.min_language_score??40;$('pfLangWeight').value=p?.language_weight??35;$('pfGerman').value=p?.current_german_level||'a2_b1';$('pfGermanMax').value=p?.max_german_requirement||'b1';$('pfKeywords').value=JSON.stringify(p?.keywords||{search:{},title:{},format:{},skill:{},negative:{}},null,2);$('pfEnabled').checked=p?.enabled??true;$('pfDefault').checked=p?.is_default??false;$('pfStretch').checked=p?.show_b2_stretch??true;$('pfHideHeavy').checked=p?.hide_german_heavy??true;$('pfGrowth').checked=p?.prefer_german_growth??true;$('profileModal').classList.add('open')};
  window.closeProfileEditor=()=>$('profileModal').classList.remove('open');
  window.saveProfileEditor=async function(){let keywords;try{keywords=JSON.parse($('pfKeywords').value||'{}')}catch(e){$('profileSaveStatus').textContent='Invalid keyword JSON';$('profileSaveStatus').className='status error';return}const id=+$('pfId').value;const payload={name:$('pfName').value.trim(),slug:$('pfSlug').value.trim()||$('pfName').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),enabled:$('pfEnabled').checked,is_default:$('pfDefault').checked,target_location:$('pfLocation').value.trim()||'Berlin',location_terms:$('pfLocations').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),min_score:+$('pfMin').value||0,min_language_score:+$('pfLangMin').value||0,language_weight:+$('pfLangWeight').value||0,current_german_level:$('pfGerman').value,max_german_requirement:$('pfGermanMax').value,show_b2_stretch:$('pfStretch').checked,hide_german_heavy:$('pfHideHeavy').checked,prefer_german_growth:$('pfGrowth').checked,keywords};try{await api(id?`/api/profiles/${id}`:'/api/profiles',{method:id?'PUT':'POST',body:JSON.stringify(payload)});toast('Profile saved');closeProfileEditor();await loadProfiles();if(window.loadReviewProfiles)await window.loadReviewProfiles()}catch(e){$('profileSaveStatus').textContent=e.message;$('profileSaveStatus').className='status error'}};
  window.removeProfile=async id=>{if(!confirm('Delete this search profile and its profile-specific scores?'))return;try{await api(`/api/profiles/${id}`,{method:'DELETE'});await loadProfiles();toast('Profile deleted')}catch(e){toast(e.message,true)}};
  window.activateProfile=async id=>{window.activeProfileId=id;try{localStorage.setItem('jobtrack-profile',String(id))}catch(e){};const sel=$('reviewProfile');if(sel)sel.value=String(id);toast('Review profile changed');if(window.loadReviewJobs)await window.loadReviewJobs()};
  install();loadProfiles().catch(()=>{});
})();
