(() => {
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); let profiles=[],guideDirty=false;
  const style=document.createElement('style');style.textContent=`.profile-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}.profile-card{position:relative}.profile-card.default{border-color:#9bb4f5}.profile-badges{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.profile-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.profile-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;z-index:100;padding:18px}.profile-modal.open{display:flex}.profile-dialog{background:#fff;border-radius:16px;max-width:900px;width:100%;max-height:92vh;overflow:auto;padding:22px;box-shadow:0 18px 60px rgba(0,0,0,.25)}.profile-dialog textarea{min-height:170px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.profile-checks{display:flex;gap:18px;flex-wrap:wrap;margin-top:10px}`;document.head.appendChild(style);
  style.textContent+=`.profile-basics{margin-bottom:14px}.profile-guide{margin:0 0 14px;padding:15px;border:1px solid #d7e2fb;border-radius:14px;background:#f7f9ff}.profile-guide summary,.profile-advanced summary{cursor:pointer;font-size:14px;font-weight:750;color:#233b72}.profile-guide-body{display:grid;gap:13px;margin-top:14px}.profile-guide-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.profile-guide-options{display:flex;gap:8px;flex-wrap:wrap}.profile-guide-option{display:inline-flex;align-items:center;gap:5px;padding:6px 9px;border:1px solid #d7dfed;border-radius:9px;background:#fff;font-size:11px}.profile-guide-preview{padding:11px;border:1px solid #e0e6f2;border-radius:10px;background:#fff}.profile-guide-preview code{display:block;padding:3px 0;color:#334155;font-size:11px}.profile-guide-checks{display:grid;gap:5px;margin-top:8px;font-size:11px}.profile-guide-ok{color:#24734e}.profile-guide-warning{color:#946200}.profile-guide-actions{display:flex;gap:8px;flex-wrap:wrap}.profile-advanced{margin-top:12px;padding:13px;border:1px solid var(--line);border-radius:12px}.profile-advanced>.form-grid{margin-top:15px}.profile-dialog>.actions{position:sticky;bottom:-22px;margin:18px -22px -22px;padding:13px 22px;background:rgba(255,255,255,.96);border-top:1px solid var(--line);justify-content:flex-end;backdrop-filter:blur(10px)}@media(max-width:700px){.profile-guide-row{grid-template-columns:1fr}.profile-guide-actions .btn,.profile-dialog>.actions .btn{width:100%}.profile-dialog>.actions{display:grid}}`;

  const GUIDE_ROLES={
    quality_technician:{label:'Quality control / technician',de:'Qualitätsprüfer',en:'quality technician',aliases:['quality technician','quality inspector','quality control technician','quality control','Qualitätstechniker','Qualitätsprüfer','Qualitätskontrolleur','Qualitätskontrolle','Mitarbeiter Qualitätssicherung','Wareneingangsprüfer','Prüftechniker']},
    quality_engineering:{label:'Quality engineering',de:'Qualitätsingenieur',en:'quality engineer',aliases:['quality engineer','quality engineering','Qualitätsingenieur','Qualitätsingenieur Produktion']},
    production:{label:'Production / manufacturing',de:'Produktionsassistenz',en:'production assistant',aliases:['production assistant','production support','Produktionsassistenz','Produktionsmitarbeiter']},
    planning:{label:'Production planning',de:'Arbeitsvorbereitung',en:'production planning',aliases:['production planning','production planner','Arbeitsvorbereitung','Produktionsplanung']},
    process:{label:'Process engineering',de:'Prozessingenieur',en:'process engineer',aliases:['process engineer','process engineering','Prozessingenieur','Prozessoptimierung']},
    office:{label:'Technical office / administration',de:'technische Sachbearbeitung',en:'technical office',aliases:['technical office','technical assistant','technische Sachbearbeitung','Projektassistenz']},
    procurement:{label:'Procurement / purchasing',de:'Einkauf',en:'procurement',aliases:['procurement','purchasing','Einkauf','Einkäufer']},
    logistics:{label:'Logistics / supply chain',de:'Logistik',en:'supply chain',aliases:['logistics','supply chain','Logistik','Lieferkette']},
  };
  const GUIDE_FORMATS={
    fulltime:{label:'Full-time / Vollzeit',de:'Vollzeit',en:'full time',terms:['Vollzeit','full time','full-time']},
    parttime:{label:'Part-time / Teilzeit',de:'Teilzeit',en:'part time',terms:['Teilzeit','part time','part-time']},
    minijob:{label:'Minijob',de:'Minijob',en:'minijob',terms:['Minijob','geringfügig']},
    student:{label:'Working student / Werkstudent',de:'Werkstudent',en:'working student',terms:['Werkstudent','working student']},
  };
  const GUIDE_PRESETS={
    quality_both:{name:'Quality technician / Full-time and part-time',roles:['quality_technician'],formats:['fulltime','parttime'],level:'technician',german:'a2_b1',english:'b1',availability:'any',hours:''},
    technical_parttime:{name:'Technical support / Part-time',roles:['quality_technician','production','planning','office'],formats:['parttime','minijob'],level:'technician',german:'a2_b1',english:'b1',availability:'afternoon',hours:20},
    engineering_fulltime:{name:'Engineering / Full-time',roles:['quality_engineering','process','planning'],formats:['fulltime'],level:'engineer',german:'b1',english:'b2',availability:'any',hours:''},
    office_minijob:{name:'Technical office / Minijob',roles:['office','procurement','logistics'],formats:['parttime','minijob'],level:'any',german:'a2_b1',english:'b1',availability:'afternoon',hours:15},
  };
  const ROLE_LEVEL_LABELS={any:'Any suitable level',technician:'Technician / inspection staff',engineer:'Engineer',student:'Working student'};

  function buildProfileGuidePlan(selection){
    const roles=(selection.roles||[]).map(key=>GUIDE_ROLES[key]).filter(Boolean);
    const formats=(selection.formats||[]).filter(key=>key!=='student'||selection.enrolled).map(key=>GUIDE_FORMATS[key]).filter(Boolean);
    const languages=selection.languages||[];
    const roleTerms=[...new Set(roles.flatMap(role=>role.aliases))];
    const formatTerms=[...new Set(formats.flatMap(format=>format.terms))];
    const batches=roles.map(role=>formats.flatMap(format=>[
      ...(languages.includes('de')?[`${role.de} ${format.de}`]:[]),
      ...(languages.includes('en')?[`${role.en} ${format.en}`]:[]),
    ]));
    const queries=[];for(let index=0;index<Math.max(0,...batches.map(batch=>batch.length));index++)for(const batch of batches)if(batch[index])queries.push(batch[index]);
    const warnings=[];
    if(!roles.length)warnings.push('Choose at least one target role.');
    if(!formats.length)warnings.push('Choose at least one eligible working arrangement.');
    if(!languages.length)warnings.push('Choose German or English provider queries.');
    if((selection.formats||[]).includes('student')&&!selection.enrolled)warnings.push('Working-student searches require current university enrollment.');
    if(selection.roleLevel==='student'&&!(selection.formats||[]).includes('student'))warnings.push('Student level requires the Working student arrangement.');
    if(selection.roleLevel==='technician'&&(selection.roles||[]).includes('quality_engineering'))warnings.push('Quality engineering conflicts with technician level.');
    if(selection.roleLevel==='engineer'&&(selection.roles||[]).includes('quality_technician'))warnings.push('Quality technician conflicts with engineering level.');
    if((selection.formats||[]).includes('fulltime')&&((selection.formats||[]).includes('parttime')||(selection.formats||[]).includes('minijob')))warnings.push('Create separate full-time and part-time profiles for more precise matches.');
    if(queries.length>8)warnings.push('Some providers only run the first 6–8 queries; role families are interleaved automatically.');
    const scheduleTerms=selection.availability==='afternoon'?['nachmittags','ab 14 Uhr','afternoon']:selection.availability==='flexible'?['flexible Arbeitszeiten','flexible working hours']:[];
    if(selection.hours&&Number(selection.hours)>0)scheduleTerms.push(`${Number(selection.hours)} Stunden`);
    return {roles:roleTerms,formats:formatTerms,queries:[...new Set(queries)],warnings,scheduleTerms};
  }
  window.profileGuideBuildPlan=buildProfileGuidePlan;

  function guideSelection(){return {
    roles:Object.keys(GUIDE_ROLES).filter(key=>$(`pfGuideRole-${key}`)?.checked),
    formats:Object.keys(GUIDE_FORMATS).filter(key=>$(`pfGuideFormat-${key}`)?.checked),
    languages:[...$('pfGuideLanguageDe')?.checked?['de']:[],...$('pfGuideLanguageEn')?.checked?['en']:[]],
    enrolled:Boolean($('pfGuideEnrolled')?.checked),availability:$('pfGuideAvailability')?.value||'any',hours:$('pfGuideHours')?.value||'',roleLevel:$('pfGuideRoleLevel')?.value||'any',
  }}
  function profileGuideLevelError(selection){if(selection.roleLevel==='student'&&!(selection.formats||[]).includes('student'))return 'Student level requires the Working student arrangement.';if(selection.roleLevel==='technician'&&(selection.roles||[]).includes('quality_engineering'))return 'Quality engineering conflicts with technician level.';if(selection.roleLevel==='engineer'&&(selection.roles||[]).includes('quality_technician'))return 'Quality technician conflicts with engineering level.';return ''}

  window.refreshProfileGuide=function(){const plan=buildProfileGuidePlan(guideSelection()),preview=$('pfGuideQueryPreview'),checks=$('pfGuideChecks');if(!preview||!checks)return plan;preview.innerHTML=plan.queries.length?plan.queries.slice(0,8).map(query=>`<code>${esc(query)}</code>`).join(''):'<span class="hint">Choose a role and working arrangement to preview search phrases.</span>';const ready=[plan.roles.length&&`${plan.roles.length} bilingual role terms`,plan.formats.length&&`${plan.formats.length} working-arrangement terms`,plan.queries.length&&`${plan.queries.length} provider-ready queries`].filter(Boolean);checks.innerHTML=[...ready.map(text=>`<div class="profile-guide-ok">✓ ${esc(text)}</div>`),...plan.warnings.map(text=>`<div class="profile-guide-warning">! ${esc(text)}</div>`)].join('');return plan};

  window.applyProfileGuidePreset=function(){const preset=GUIDE_PRESETS[$('pfGuidePreset')?.value];if(!preset)return;Object.keys(GUIDE_ROLES).forEach(key=>{$(`pfGuideRole-${key}`).checked=preset.roles.includes(key)});Object.keys(GUIDE_FORMATS).forEach(key=>{$(`pfGuideFormat-${key}`).checked=preset.formats.includes(key)});$('pfGuideRoleLevel').value=preset.level;$('pfGuideGerman').value=preset.german;$('pfGuideEnglish').value=preset.english;$('pfGuideAvailability').value=preset.availability;$('pfGuideHours').value=preset.hours;$('pfGuideLanguageDe').checked=true;$('pfGuideLanguageEn').checked=true;$('pfGuideEnrolled').checked=preset.level==='student';guideDirty=true;if(!$('pfName').value.trim())$('pfName').value=preset.name;return refreshProfileGuide()};

  function mergeGuideTerms(id,terms){const existing=$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);$(id).value=[...new Set([...existing,...terms])].join('\n')}
  window.applyProfileGuide=function(silent=false){const selection=guideSelection(),plan=buildProfileGuidePlan(selection),levelError=profileGuideLevelError(selection);if(levelError||!plan.roles.length||!plan.formats.length||!plan.queries.length){refreshProfileGuide();if(!silent)toast(levelError||'Complete the profile guide before applying suggestions',true);return false}mergeGuideTerms('pfRolePhrases',plan.roles);mergeGuideTerms('pfFormatPhrases',plan.formats);mergeGuideTerms('pfSearchPhrases',plan.queries);$('pfGermanMax').value=['a1','a2'].includes($('pfGuideGerman').value)?'a2':$('pfGuideGerman').value==='b2'?'b2':'b1';$('pfContentDe').checked=selection.languages.includes('de');$('pfContentEn').checked=selection.languages.includes('en');$('pfContentMixed').checked=selection.languages.length>1;let keywords;try{keywords=JSON.parse($('pfKeywords').value||'{}')}catch(_){keywords={}}keywords.language={[`english_${$('pfGuideEnglish').value}`]:0};$('pfKeywords').value=JSON.stringify(keywords,null,2);guideDirty=false;refreshProfileGuide();if(!silent)toast('Suggestions added; existing custom terms were preserved');return true};

  function hydrateProfileGuide(profile){if(!$('pfGuidePreset'))return;const keywords=profile?.keywords||{},titleTerms=Object.keys(keywords.title||{}).map(term=>term.toLowerCase()),formatTerms=Object.keys(keywords.format||{}).map(term=>term.toLowerCase());Object.entries(GUIDE_ROLES).forEach(([key,role])=>{$(`pfGuideRole-${key}`).checked=role.aliases.some(alias=>titleTerms.includes(alias.toLowerCase()))});Object.entries(GUIDE_FORMATS).forEach(([key,format])=>{$(`pfGuideFormat-${key}`).checked=format.terms.some(term=>formatTerms.includes(term.toLowerCase()))});$('pfGuideRoleLevel').value=profile?.role_level||'any';$('pfGuideGerman').value=profile?.current_german_level||'a2_b1';const englishKey=Object.keys(keywords.language||{}).find(term=>term.startsWith('english_'));$('pfGuideEnglish').value=profile?.current_english_level||englishKey?.slice(8)||'b1';$('pfGuideLanguageDe').checked=(profile?.content_languages||['de','en']).includes('de');$('pfGuideLanguageEn').checked=(profile?.content_languages||['de','en']).includes('en');$('pfGuideEnrolled').checked=(profile?.role_level==='student')||formatTerms.some(term=>['werkstudent','working student'].includes(term));$('pfGuideAvailability').value=profile?.availability||'any';$('pfGuideHours').value=profile?.preferred_weekly_hours??'';$('pfGuidePreset').value='';guideDirty=false;refreshProfileGuide()}

  function install(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('profiles'))return;const b=document.createElement('button');b.dataset.tab='profiles';b.textContent='Profiles';nav.insertBefore(b,nav.querySelector('[data-tab="search"]')||null);const s=document.createElement('section');s.id='profiles';s.className='section';s.innerHTML=`<div class="section-title"><div><h2>Search Profiles</h2><div class="hint">Each profile has independent scoring, language thresholds and learned preferences.</div></div><button class="btn primary" onclick="openProfileEditor()">New profile</button></div><div id="profileGrid" class="profile-grid"></div>`;main.appendChild(s);b.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Profiles';loadProfiles()});
    const modal=document.createElement('div');modal.id='profileModal';modal.className='profile-modal';modal.innerHTML=`<div class="profile-dialog"><div class="section-title" style="margin-top:0"><h2 id="profileModalTitle">Search profile</h2><button class="btn" onclick="closeProfileEditor()">Close</button></div><input type="hidden" id="pfId">
      <div class="profile-basics profile-guide-row"><div class="field"><label for="pfName">Profile name</label><input id="pfName"></div><div class="field"><label for="pfLocation">Primary location</label><input id="pfLocation" value="Berlin"></div></div>
      <details id="pfProfileGuide" class="profile-guide" open><summary>Profile essentials</summary><div class="profile-guide-body">
        <div class="hint">Choose the target level, roles, working arrangements and language ability. Saving also adds the generated search suggestions without removing custom terms.</div>
        <div class="profile-guide-row"><div class="field"><label for="pfGuidePreset">Start with a profile example</label><select id="pfGuidePreset"><option value="">Choose an example</option><option value="quality_both">Quality technician · full-time + part-time</option><option value="technical_parttime">Technical support · part-time</option><option value="engineering_fulltime">Engineering · full-time</option><option value="office_minijob">Technical office · minijob</option></select></div><div class="field"><label for="pfGuideRoleLevel">Target role level</label><select id="pfGuideRoleLevel"><option value="any">Any suitable level</option><option value="technician">Technician / inspection staff</option><option value="engineer">Engineer</option><option value="student">Working student</option></select></div></div>
        <div><label>1. Which positions match your experience?</label><div class="profile-guide-options">${Object.entries(GUIDE_ROLES).map(([key,role])=>`<label class="profile-guide-option"><input id="pfGuideRole-${key}" type="checkbox"> ${esc(role.label)}</label>`).join('')}</div></div>
        <div><label>2. Which working arrangements are acceptable?</label><div class="profile-guide-options">${Object.entries(GUIDE_FORMATS).map(([key,format])=>`<label class="profile-guide-option"><input id="pfGuideFormat-${key}" type="checkbox"> ${esc(format.label)}</label>`).join('')}<label class="profile-guide-option"><input id="pfGuideEnrolled" type="checkbox"> Currently enrolled at a university</label></div></div>
        <div class="profile-guide-row"><div class="field"><label>Preferred weekly hours</label><input id="pfGuideHours" type="number" min="1" max="48" placeholder="20"></div><div class="field"><label>Availability</label><select id="pfGuideAvailability"><option value="any">Any suitable time</option><option value="afternoon">Afternoons / after 14:00</option><option value="flexible">Flexible working hours</option></select></div></div>
        <div class="profile-guide-row"><div class="field"><label>Current German ability</label><select id="pfGuideGerman"><option value="a1">A1</option><option value="a2">A2</option><option value="a2_b1">A2 → B1</option><option value="b1">B1</option><option value="b2">B2</option></select></div><div class="field"><label>Current English ability</label><select id="pfGuideEnglish"><option value="a2">A2</option><option value="b1">B1</option><option value="b2">B2</option><option value="c1">C1</option><option value="c2">C2</option></select></div></div>
        <div><label>3. Which languages should job-board searches use?</label><div class="profile-guide-options"><label class="profile-guide-option"><input id="pfGuideLanguageDe" type="checkbox" checked> German job titles</label><label class="profile-guide-option"><input id="pfGuideLanguageEn" type="checkbox" checked> English job titles</label></div></div>
        <div class="profile-guide-preview"><label>4. Preview provider-ready search phrases</label><div id="pfGuideQueryPreview"></div><div id="pfGuideChecks" class="profile-guide-checks"></div></div>
        <div class="profile-guide-actions"><button class="btn" type="button" onclick="applyProfileGuide()">Add suggestions now</button><button class="btn" type="button" onclick="refreshProfileGuide()">Check profile targeting</button></div>
      </div></details><details id="pfAdvanced" class="profile-advanced"><summary>Advanced matching settings</summary><div class="form-grid">
      <div class="field"><label for="pfSlug">Slug</label><input id="pfSlug"></div><div class="field"><label for="pfLocations">Location terms</label><input id="pfLocations" placeholder="berlin,potsdam,hennigsdorf"></div>
      <div class="field"><label>Minimum Overall Fit</label><input id="pfMin" type="number" min="0" max="100"></div><div class="field"><label>Minimum Language Fit</label><input id="pfLangMin" type="number" min="0" max="100"></div>
      <div class="field"><label>Language weight %</label><input id="pfLangWeight" type="number" min="0" max="100"></div>
      <div class="field"><label>Maximum preferred German</label><select id="pfGermanMax"><option value="a2">A2</option><option value="b1">B1</option><option value="b2">B2</option></select></div>
      <div class="field"><label>Preferred ad languages</label><div><label><input id="pfContentDe" type="checkbox"> German</label> <label><input id="pfContentEn" type="checkbox"> English</label> <label><input id="pfContentMixed" type="checkbox"> Mixed</label> <label><input id="pfContentUnknown" type="checkbox"> Unknown</label></div><div class="hint">Used by the “Profile preference” filter; ads are never deleted.</div></div>
      <div class="field full"><label>Provider search phrases</label><textarea id="pfSearchPhrases" style="min-height:105px" placeholder="Qualitätskontrolle Teilzeit&#10;production planning part time&#10;technische Sachbearbeitung Minijob"></textarea><div class="hint">One phrase per line. These are provider queries, not scoring rules.</div></div>
      <div class="field"><label>Target positions and roles</label><textarea id="pfRolePhrases" style="min-height:105px" placeholder="quality control&#10;production planning&#10;Sachbearbeitung"></textarea><div class="hint">One role per line. Used for role matching and bilingual expansion.</div></div>
      <div class="field"><label>Working arrangements</label><textarea id="pfFormatPhrases" style="min-height:105px" placeholder="Teilzeit&#10;Minijob&#10;part time"></textarea><div class="hint">One format per line. Part-time hours are also recognized automatically.</div></div>
      <div class="field full"><label>Advanced scoring keywords (JSON)</label><textarea id="pfKeywords"></textarea><div class="hint">Sections: search, title, format, skill, allowlist, blocklist and legacy negative. Allowlist weights are positive boosts; every blocklist match is a hard exclusion.</div></div>
    </div><div class="profile-checks"><label><input type="checkbox" id="pfEnabled"> Enabled</label><label><input type="checkbox" id="pfDefault"> Default profile</label><label><input type="checkbox" id="pfStretch"> Show B2 stretch</label><label><input type="checkbox" id="pfHideHeavy"> Hide German-heavy</label><label><input type="checkbox" id="pfGrowth"> Prefer German-growth</label></div></details><div class="actions"><button class="btn" onclick="closeProfileEditor()">Cancel</button><button class="btn primary" onclick="saveProfileEditor()">Save profile</button><span id="profileSaveStatus" class="status"></span></div></div>`;document.body.appendChild(modal);modal.querySelectorAll('#pfProfileGuide input,#pfProfileGuide select').forEach(input=>input.addEventListener('change',()=>{guideDirty=true;refreshProfileGuide()}));
  }

  window.loadProfiles=async function(){const d=await api('/api/profiles');profiles=d.profiles;const grid=$('profileGrid');if(grid)grid.innerHTML=profiles.map(p=>`<div class="card profile-card ${p.is_default?'default':''}"><div class="source-title">${esc(p.name)}</div><div class="profile-badges"><span class="pill">${p.enabled?'Enabled':'Disabled'}</span>${p.is_default?'<span class="pill">Default</span>':''}<span class="pill">${esc(ROLE_LEVEL_LABELS[p.role_level]||ROLE_LEVEL_LABELS.any)}</span><span class="pill">DE ${esc(p.current_german_level.replace('_',' → ').toUpperCase())}</span><span class="pill">EN ${esc((p.current_english_level||'b1').toUpperCase())}</span>${p.preferred_weekly_hours?`<span class="pill">${p.preferred_weekly_hours}h/week</span>`:''}</div><div class="muted">${esc(p.target_location)} · min ${p.min_score} · language min ${p.min_language_score} · language weight ${p.language_weight}%</div><div class="hint" style="margin-top:8px">${Object.keys(p.keywords?.search||{}).length} search phrases · ${Object.keys(p.keywords?.allowlist||{}).length} allowlist · ${Object.keys(p.keywords?.blocklist||{}).length} blacklist</div><div class="profile-actions"><button class="btn" onclick="openProfileEditor(${p.id})">Edit</button><button class="btn" onclick="activateProfile(${p.id})">Use in review</button>${p.is_default?'':`<button class="btn danger" onclick="removeProfile(${p.id})">Delete</button>`}</div></div>`).join('');return profiles};

  window.openProfileEditor=function(id){const p=id?profiles.find(x=>x.id===id):null,content=p?.content_languages||['de','en','mixed'];$('pfId').value=p?.id||'';$('profileModalTitle').textContent=p?'Edit search profile':'New search profile';$('profileSaveStatus').textContent='';$('pfName').value=p?.name||'';$('pfSlug').value=p?.slug||'';$('pfLocation').value=p?.target_location||'Berlin';$('pfLocations').value=(p?.location_terms||['berlin']).join(',');$('pfMin').value=p?.min_score??35;$('pfLangMin').value=p?.min_language_score??40;$('pfLangWeight').value=p?.language_weight??35;$('pfGermanMax').value=p?.max_german_requirement||'b1';$('pfContentDe').checked=content.includes('de');$('pfContentEn').checked=content.includes('en');$('pfContentMixed').checked=content.includes('mixed');$('pfContentUnknown').checked=content.includes('unknown');$('pfKeywords').value=JSON.stringify(p?.keywords||{search:{},title:{},format:{},skill:{},allowlist:{},blocklist:{},negative:{}},null,2);$('pfSearchPhrases').value=Object.keys(p?.keywords?.search||{}).join('\n');$('pfRolePhrases').value=Object.keys(p?.keywords?.title||{}).join('\n');$('pfFormatPhrases').value=Object.keys(p?.keywords?.format||{}).join('\n');$('pfEnabled').checked=p?.enabled??true;$('pfDefault').checked=p?.is_default??false;$('pfStretch').checked=p?.show_b2_stretch??true;$('pfHideHeavy').checked=p?.hide_german_heavy??true;$('pfGrowth').checked=p?.prefer_german_growth??true;$('pfAdvanced').open=false;hydrateProfileGuide(p);$('profileModal').classList.add('open')};
  window.closeProfileEditor=()=>$('profileModal').classList.remove('open');
  window.saveProfileEditor=async function(){const selection=guideSelection(),levelError=profileGuideLevelError(selection);if(levelError){$('profileSaveStatus').textContent=levelError;$('profileSaveStatus').className='status error';return}if(guideDirty)applyProfileGuide(true);let keywords;try{keywords=JSON.parse($('pfKeywords').value||'{}')}catch(e){$('profileSaveStatus').textContent='Invalid keyword JSON';$('profileSaveStatus').className='status error';$('pfAdvanced').open=true;return}for(const [section,id,weight] of [['search','pfSearchPhrases',0],['title','pfRolePhrases',28],['format','pfFormatPhrases',16]]){const previous=keywords[section]||{};keywords[section]=Object.fromEntries($(id).value.split('\n').map(x=>x.trim()).filter(Boolean).map(term=>[term,Object.prototype.hasOwnProperty.call(previous,term)?previous[term]:weight]))}const id=+$('pfId').value,content_languages=[['pfContentDe','de'],['pfContentEn','en'],['pfContentMixed','mixed'],['pfContentUnknown','unknown']].filter(x=>$(x[0]).checked).map(x=>x[1]),hours=$('pfGuideHours').value?+$('pfGuideHours').value:null;const payload={name:$('pfName').value.trim(),slug:$('pfSlug').value.trim()||$('pfName').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),enabled:$('pfEnabled').checked,is_default:$('pfDefault').checked,target_location:$('pfLocation').value.trim()||'Berlin',location_terms:$('pfLocations').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),min_score:+$('pfMin').value||0,min_language_score:+$('pfLangMin').value||0,language_weight:+$('pfLangWeight').value||0,current_german_level:$('pfGuideGerman').value,current_english_level:$('pfGuideEnglish').value,max_german_requirement:$('pfGermanMax').value,preferred_weekly_hours:hours,availability:$('pfGuideAvailability').value,role_level:$('pfGuideRoleLevel').value,content_languages,show_b2_stretch:$('pfStretch').checked,hide_german_heavy:$('pfHideHeavy').checked,prefer_german_growth:$('pfGrowth').checked,keywords};try{await api(id?`/api/profiles/${id}`:'/api/profiles',{method:id?'PUT':'POST',body:JSON.stringify(payload)});toast('Profile saved');closeProfileEditor();await loadProfiles();if(window.loadReviewProfiles)await window.loadReviewProfiles()}catch(e){$('profileSaveStatus').textContent=e.message;$('profileSaveStatus').className='status error'}};
  window.removeProfile=async id=>{if(!confirm('Delete this search profile and its profile-specific scores?'))return;try{await api(`/api/profiles/${id}`,{method:'DELETE'});await loadProfiles();toast('Profile deleted')}catch(e){toast(e.message,true)}};
  window.activateProfile=async id=>{window.activeProfileId=id;try{localStorage.setItem('jobtrack-profile',String(id))}catch(e){};const sel=$('reviewProfile');if(sel)sel.value=String(id);toast('Review profile changed');if(window.loadReviewJobs)await window.loadReviewJobs()};
  install();loadProfiles().catch(()=>{});
  if(!document.querySelector('script[src="/search-job-ui.js"]')){const sc=document.createElement('script');sc.src='/search-job-ui.js';document.body.appendChild(sc)}
})();
