(() => {
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const reasonOptions=[['wrong_role','Wrong role / function'],['german_level','German requirement too high'],['seniority','Wrong seniority'],['employment_type','Wrong employment type'],['location','Wrong location'],['company','Not interested in company'],['other','Other']];
  window.activeProfileId=window.activeProfileId||null;

  function injectStyles(){const st=document.createElement('style');st.textContent=`
    .review-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:end;margin-bottom:18px;padding:14px;background:#fff;border:1px solid var(--line);border-radius:12px}.review-toolbar .field{min-width:150px;flex:1}.review-toolbar .profile-field{min-width:220px;flex:1.35}
    .job-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:14px}.job-card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:17px;box-shadow:var(--shadow);display:flex;flex-direction:column;gap:13px;cursor:pointer;transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease}.job-card:hover{border-color:var(--accent);box-shadow:0 12px 30px rgba(15,23,42,.09);transform:translateY(-1px)}.job-card:focus-visible{outline:3px solid var(--focus);outline-offset:3px}
    .job-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.job-heading{min-width:0}.job-title{display:block;color:var(--text);font-weight:780;font-size:16px;line-height:1.35;letter-spacing:-.012em}.job-company{color:var(--muted);margin-top:6px;font-size:13px}.job-score{display:grid;place-items:center;min-width:48px;height:48px;border-radius:12px;background:var(--accent2);color:var(--accent);font-size:18px;font-weight:800}.job-labels{display:flex;gap:5px;flex-wrap:wrap}.job-labels .pill{margin:0;background:var(--surface-soft);color:var(--muted);border:1px solid var(--line)}.job-labels button.pill{cursor:pointer;font:inherit;font-size:11px}
    .fit-row{display:grid;grid-template-columns:1.25fr 1fr 1fr;border:1px solid #e2e7ee;border-radius:12px;overflow:hidden;background:#f8fafc}.fit-box{position:relative;padding:11px 12px;background:transparent;border-right:1px solid #e2e7ee}.fit-box:last-child{border-right:0}.fit-box b{display:block;font-size:20px;line-height:1.1;color:#243247}.fit-box span{font-size:11px;color:var(--muted)}.fit-box:first-child b{color:var(--accent)}
    .review-actions{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:7px;margin-top:auto;padding-top:2px}.review-actions button{min-width:0}.btn.suitable{background:var(--accent);color:#fff;border-color:var(--accent)}.btn.suitable:hover{background:#1d4fc4}.btn.maybe2{background:#fff;color:#334155;border-color:#cbd5e1}.btn.unsuitable{background:#fff;color:#7f1d1d;border-color:#e1c5c2}
    .job-meta{font-size:11px;color:var(--muted);display:flex;gap:0;flex-wrap:wrap;border-top:1px solid #edf0f4;padding-top:11px}.job-meta span{display:flex;align-items:center}.job-meta span:not(:last-child)::after{content:'·';margin:0 7px;color:#a6afbc}.why-list{font-size:12px;color:#526174;display:flex;gap:6px;flex-wrap:wrap;max-height:58px;overflow:hidden}.why-list .pill{margin:0;background:#f3f5f8;color:#475569;border:1px solid transparent;border-radius:7px;padding:4px 7px}
    .job-insights{display:flex;gap:6px;flex-wrap:wrap}.job-insight{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:8px;background:var(--accent2);color:var(--accent);font-size:11px;font-weight:640}.job-insight.schedule,.job-insight.language,.job-insight.fresh,.job-insight.unknown{background:var(--surface-soft);color:var(--muted)}.job-recommendation{font-size:11px;font-weight:720;color:var(--accent)}.job-card.fit-priority{border-color:color-mix(in srgb,var(--accent) 40%,var(--line))}.job-card-hint{margin-top:auto;color:var(--muted);font-size:11px}
    .job-detail-backdrop{position:fixed;inset:0;z-index:120;display:grid;place-items:center;padding:18px;background:rgba(8,15,28,.64);backdrop-filter:blur(5px)}.job-detail-backdrop[hidden]{display:none}.job-detail{width:min(820px,100%);max-height:min(860px,92dvh);overflow:auto;background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:18px;box-shadow:0 28px 90px rgba(2,6,23,.35)}.job-detail-head{display:flex;justify-content:space-between;gap:18px;position:sticky;top:0;padding:20px 22px 14px;background:var(--card);border-bottom:1px solid var(--line);z-index:2}.job-detail-head h2{margin:0;font-size:21px}.job-detail-close{width:42px;height:42px;padding:0;font-size:20px}.job-detail-body{display:grid;gap:20px;padding:20px 22px 24px}.job-detail-section h3{margin:0 0 8px;font-size:13px}.job-detail-description{white-space:pre-wrap;line-height:1.65;color:var(--text);overflow-wrap:anywhere}.job-detail-actions{display:flex;gap:8px;flex-wrap:wrap}.job-detail-actions .btn{display:inline-flex;align-items:center;justify-content:center}.job-detail-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.job-detail-fact{padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--surface-soft)}.job-detail-fact b{display:block;font-size:16px}.job-detail-fact span{font-size:11px;color:var(--muted)}
    .learning-rule{display:grid;grid-template-columns:90px 90px 1fr 80px 110px auto;gap:10px;align-items:center;padding:10px 12px;border-bottom:1px solid var(--line)}
    .rule-term{font-weight:700}.reject-box{display:grid;grid-template-columns:1fr;gap:8px;padding:12px;background:#fafafa;border:1px solid #e2e7ee;border-radius:10px}.reject-box textarea{min-height:54px;border:1px solid var(--line);border-radius:8px;padding:8px;resize:vertical}.reject-box select{padding:8px}.polarity-boost{background:#eef2f7;color:#334155}.polarity-penalty{background:#eef2f7;color:#334155}
    @media(max-width:700px){.review-toolbar{display:grid;padding:12px}.review-toolbar .field,.review-toolbar .profile-field{min-width:0}.job-grid{grid-template-columns:1fr}.job-card{padding:15px;gap:12px}.learning-rule{grid-template-columns:1fr 1fr}.review-actions{grid-template-columns:1fr}.review-actions .btn{width:100%}.job-detail-backdrop{padding:0;align-items:end}.job-detail{max-height:94dvh;border-radius:18px 18px 0 0}.job-detail-head,.job-detail-body{padding-inline:16px}.job-detail-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.job-detail-actions{display:grid}.job-detail-actions .btn{width:100%}}
    @media(prefers-reduced-motion:reduce){.job-card{transition:none}.job-card:hover{transform:none}}`;document.head.appendChild(st)}
  function fitClass(n){return n>=75?'fit-high':n>=50?'fit-mid':'fit-low'}
  function insightMarkup(job){const reasons=job.reasons||[],language=job.language_reasons||[];const role=reasons.find(x=>x.startsWith('role family:')||x.startsWith('title:'));const schedule=job.schedule_label||reasons.find(x=>x.startsWith('schedule:'))||reasons.find(x=>x.startsWith('format:'));const scheduleDetail=schedule?.replace(/^(?:schedule|format):\s*/, '');const languageReason=language.find(x=>/German|English|level/i.test(x));return [`<span class="job-insight role">◈ ${esc(job.primary_category||role?.replace(/^(?:role family|title):\s*/, '')||'Other')}</span>`,`<span class="job-insight schedule ${job.employment_type==='unknown'?'unknown':''}">◷ ${esc(job.employment_label||'Work time unknown')}${job.weekly_hours?` · ${job.weekly_hours}h/week`:''}${scheduleDetail?` · ${esc(scheduleDetail)}`:''}</span>`,`<span class="job-insight fresh">◉ ${esc(job.freshness_label||'Date unknown')}</span>`,job.job_level&&job.job_level!=='Unspecified'?`<span class="job-insight role">⌁ ${esc(job.job_level)}</span>`:'',languageReason?`<span class="job-insight language">◎ ${esc(languageReason)}</span>`:''].join('')}

  function installOverview(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('jobReview'))return;const button=document.createElement('button');button.dataset.tab='jobReview';button.textContent='Job Review';nav.appendChild(button);const section=document.createElement('section');section.id='jobReview';section.className='section';section.innerHTML=`
    <div class="section-title"><div><h2>Job Review Queue</h2><div class="hint">Scores and learning are calculated independently for the selected search profile.</div></div></div>
    <div class="review-toolbar">
      <div class="field profile-field"><label>Search profile</label><select id="reviewProfile"><option>Loading…</option></select></div>
      <div class="field"><label>Decision</label><select id="reviewDecision"><option value="active">Active</option><option value="unreviewed">Unreviewed</option><option value="apply">Suitable</option><option value="maybe">Maybe</option><option value="skip">Not suitable</option><option value="all">All</option></select></div>
      <div class="field"><label>Language requirement</label><select id="reviewLanguage"><option value="preferred">Recommended</option><option value="english_first">English-first</option><option value="german_growth">German-growth</option><option value="stretch">B2 stretch</option><option value="unclear">Unclear</option><option value="all">All</option></select></div>
      <div class="field"><label>Ad language</label><select id="reviewContentLanguage"><option value="profile">Profile preference</option><option value="de">German (DE)</option><option value="en">English (EN)</option><option value="mixed">Mixed (DE/EN)</option><option value="unknown">Unknown</option><option value="all">All</option></select></div>
      <div class="field"><label>Min fit</label><input id="reviewMin" type="number" value="35" min="0" max="100"></div><button class="btn" id="reviewReload">Refresh jobs</button>
    </div><div id="jobReviewGrid" class="job-grid"></div>
    <div id="jobDetailBackdrop" class="job-detail-backdrop" hidden><article class="job-detail" role="dialog" aria-modal="true" aria-labelledby="jobDetailTitle"><header class="job-detail-head"><div><h2 id="jobDetailTitle">Job details</h2><div id="jobDetailSubtitle" class="muted"></div></div><button id="jobDetailClose" class="btn job-detail-close" type="button" aria-label="Close job details">×</button></header><div id="jobDetailBody" class="job-detail-body"></div></article></div>`;main.appendChild(section);button.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button[data-tab]').forEach(x=>x.classList.remove('active'));section.classList.add('active');button.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Job Review';window.loadReviewJobs()});
    const overview=$('overview');const oldTitle=overview?[...overview.querySelectorAll('.section-title')].find(x=>x.textContent.includes('Latest matches')):null;const oldTable=oldTitle?.nextElementSibling;if(oldTitle)oldTitle.remove();if(oldTable?.classList.contains('table-wrap'))oldTable.remove();
    ['reviewDecision','reviewLanguage','reviewContentLanguage','reviewMin'].forEach(id=>$(id).addEventListener('change',window.loadReviewJobs));$('reviewReload').addEventListener('click',window.loadReviewJobs);$('reviewProfile').addEventListener('change',()=>{window.activeProfileId=+$('reviewProfile').value;try{localStorage.setItem('jobtrack-profile',String(window.activeProfileId))}catch(e){};window.loadReviewJobs();if($('learning')?.classList.contains('active'))window.loadLearning()});$('jobDetailClose').addEventListener('click',window.closeJobDetail);$('jobDetailBackdrop').addEventListener('click',event=>{if(event.target===$('jobDetailBackdrop'))window.closeJobDetail()});
  }

  function installLearning(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('learning'))return;const b=document.createElement('button');b.dataset.tab='learning';b.textContent='Learning';nav.appendChild(b);const s=document.createElement('section');s.id='learning';s.className='section';s.innerHTML=`
    <div class="section-title"><div><h2>Profile Learning</h2><div class="hint">Boost and penalty rules belong only to the active search profile.</div></div><button class="btn" onclick="loadLearning()">Refresh</button></div>
    <div class="grid"><div class="card"><div class="muted">Positive events</div><div id="lfPositive" class="metric">—</div></div><div class="card"><div class="muted">Active boosts</div><div id="lfBoosts" class="metric">—</div></div><div class="card"><div class="muted">Not suitable</div><div id="lfBad" class="metric">—</div></div><div class="card"><div class="muted">Active penalties</div><div id="lfPenalties" class="metric">—</div></div></div>
    <div class="section-title"><h2>Learned preference rules</h2></div><div class="card" style="padding:0"><div id="learnedRules"></div></div>
    <div class="section-title"><h2>Recent review feedback</h2></div><div class="table-wrap"><table><thead><tr><th>Job</th><th>Decision</th><th>Reason</th><th>When</th></tr></thead><tbody id="feedbackBody"></tbody></table></div>`;main.appendChild(s);b.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Learning';window.loadLearning()})}

  window.loadReviewProfiles=async function(){const d=await api('/api/profiles');const sel=$('reviewProfile');if(!sel)return;let saved=null;try{saved=+localStorage.getItem('jobtrack-profile')}catch(e){};const active=d.profiles.find(p=>p.id===saved&&p.enabled)||d.profiles.find(p=>p.is_default)||d.profiles.find(p=>p.enabled)||d.profiles[0];window.activeProfileId=active?.id||null;sel.innerHTML=d.profiles.length?d.profiles.filter(p=>p.enabled).map(p=>`<option value="${p.id}" ${p.id===window.activeProfileId?'selected':''}>${esc(p.name)}${p.is_default?' · default':''}</option>`).join(''):'<option value="">Create a search profile first</option>';if(active)$('reviewMin').value=active.min_score??35;return d.profiles};

  window.loadReviewJobs=async function(){if(!window.activeProfileId)await window.loadReviewProfiles();const grid=$('jobReviewGrid');if(!grid)return;if(!window.activeProfileId){grid.innerHTML='<div class="card muted">Create a search profile to start reviewing jobs.</div>';return}const q=new URLSearchParams({limit:'150',min_score:$('reviewMin')?.value||'35',decision:$('reviewDecision')?.value||'active',language:$('reviewLanguage')?.value||'preferred',content_language:$('reviewContentLanguage')?.value||'profile',profile_id:String(window.activeProfileId)});const d=await api('/api/jobs?'+q);grid.innerHTML=d.jobs.length?d.jobs.map((j,i)=>`<article class="job-card ${j.overall_score>=75?'fit-priority':''}" tabindex="0" role="button" aria-label="View details for ${esc(j.title)}" onclick='if(!event.target.closest("button,a,input,select,textarea"))openJobDetail(${JSON.stringify(j.job_key)},this)' onkeydown='if((event.key==="Enter"||event.key===" ")&&!event.target.closest("button,a,input,select,textarea")){event.preventDefault();openJobDetail(${JSON.stringify(j.job_key)},this)}'>
    <div class="job-head"><div class="job-heading"><span class="job-title">${esc(j.title)}</span><div class="job-company">${esc(j.company||'Company not stated')} · ${esc(j.location||'Location not stated')}</div></div><div class="job-score" title="Overall fit">${j.overall_score}</div></div>
    ${j.overall_score>=75?'<div class="job-recommendation">Strong profile match</div>':''}<div class="job-labels"><button class="pill" title="${Math.round((j.content_language_confidence||0)*100)}% confidence · ${esc(j.content_language_source)}; click to correct" onclick='editContentLanguage(${JSON.stringify(j.job_key)},${JSON.stringify(j.content_language)})'>${j.content_language==='de'?'DE':j.content_language==='en'?'EN':j.content_language==='mixed'?'DE/EN':'?'}</button><span class="pill">${esc(j.employment_label||'Work time unknown')}</span><span class="pill">${esc(j.freshness_label||'Date unknown')}</span></div>
    <div class="job-card-hint">Click for scores, description and listing link</div>
    <div class="review-actions"><button class="btn suitable" onclick='reviewJob(${JSON.stringify(j.job_key)},"suitable")'>Suitable</button><button class="btn maybe2" onclick='reviewJob(${JSON.stringify(j.job_key)},"maybe")'>Maybe</button><button class="btn unsuitable" onclick="toggleReject(${i})">Not suitable</button></div>
    <div class="reject-box" id="reject-${i}" hidden><select id="reject-reason-${i}">${reasonOptions.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><textarea id="reject-note-${i}" placeholder="Optional note"></textarea><label class="hint"><input id="reject-learn-${i}" type="checkbox" checked> Learn only for ${esc(d.profile.name)}</label><button class="btn unsuitable" onclick='submitNotSuitable(${JSON.stringify(j.job_key)},${i})'>Save as not suitable</button></div>
    </article>`).join(''):'<div class="card muted">No jobs match this profile and filters.</div>'};

  let detailTrigger=null;
  window.openJobDetail=async function(jobKey,trigger){detailTrigger=trigger||document.activeElement;const backdrop=$('jobDetailBackdrop'),body=$('jobDetailBody');backdrop.hidden=false;document.body.classList.add('jt-dialog-open');$('jobDetailTitle').textContent='Loading job…';$('jobDetailSubtitle').textContent='';body.innerHTML='<div class="muted">Loading details…</div>';$('jobDetailClose').focus();try{const d=await api(`/api/jobs/${encodeURIComponent(jobKey)}/detail?profile_id=${encodeURIComponent(window.activeProfileId)}`),j=d.job,description=j.description||j.description_preview;$('jobDetailTitle').textContent=j.title||'Job details';$('jobDetailSubtitle').textContent=`${j.company||'Company not stated'} · ${j.location||'Location not stated'}`;body.innerHTML=`<div class="job-detail-facts"><div class="job-detail-fact"><b>${j.overall_score}</b><span>Overall fit</span></div><div class="job-detail-fact"><b>${j.score}</b><span>Job fit</span></div><div class="job-detail-fact"><b>${j.language_score}</b><span>Language fit</span></div><div class="job-detail-fact"><b>${esc(j.employment_label||'Unknown')}</b><span>Working time</span></div><div class="job-detail-fact"><b>${esc(j.schedule_label||'Unknown')}</b><span>Schedule</span></div><div class="job-detail-fact"><b>${esc(j.primary_category||'Other')}</b><span>Category</span></div><div class="job-detail-fact"><b>${esc(j.published_date||'Unknown')}</b><span>Published</span></div><div class="job-detail-fact"><b>${esc(j.postal_code||'—')}</b><span>Postal code</span></div><div class="job-detail-fact"><b>${j.data_quality||0}%</b><span>Data completeness</span></div><div class="job-detail-fact"><b>${esc(j.source||'Unknown')}</b><span>Source</span></div></div><section class="job-detail-section"><h3>Match evidence</h3><div class="why-list">${(j.reasons||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')||'<span class="muted">No scoring evidence available.</span>'}</div>${(j.language_reasons||[]).length?`<div class="job-language-reasons">${j.language_reasons.map(esc).join(' · ')}</div>`:''}</section><section class="job-detail-section"><h3>Job description</h3><div class="job-detail-description">${esc(description||'No description was provided by the source.')}</div></section><div class="job-detail-actions"><a class="btn primary" href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">Open original listing ↗</a><button class="btn" type="button" onclick="closeJobDetail()">Close</button></div>`}catch(error){body.innerHTML=`<div class="error">${esc(error.message)}</div>`}};
  window.closeJobDetail=function(){const backdrop=$('jobDetailBackdrop');if(!backdrop||backdrop.hidden)return;backdrop.hidden=true;document.body.classList.remove('jt-dialog-open');detailTrigger?.focus?.();detailTrigger=null};
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('jobDetailBackdrop')?.hidden)window.closeJobDetail()});

  window.reviewJob=async function(jobKey,suitability,reason='',note='',learn=true){await api(`/api/jobs/${encodeURIComponent(jobKey)}/feedback`,{method:'POST',body:JSON.stringify({suitability,reason,note,learn,profile_id:window.activeProfileId})});toast(suitability==='suitable'?'Added to To Apply; preference learned for this profile':'Feedback saved');await window.loadReviewJobs();if(window.loadOverview)loadOverview()};
  window.editContentLanguage=async function(jobKey,current){if(window.APP_SHELL&&!window.APP_SHELL.isAdmin){toast('Only an administrator can change shared job-ad language metadata',true);return}const value=prompt('Ad language: de, en, mixed, unknown, or auto',current||'auto');if(value===null)return;try{await api(`/api/jobs/${encodeURIComponent(jobKey)}/content-language`,{method:'PUT',body:JSON.stringify({language:value.trim().toLowerCase()})});toast('Ad language updated');await window.loadReviewJobs()}catch(e){toast(e.message,true)}};
  window.toggleReject=i=>{const box=$(`reject-${i}`);box.hidden=!box.hidden};window.submitNotSuitable=async(jobKey,i)=>window.reviewJob(jobKey,'not_suitable',$(`reject-reason-${i}`).value,$(`reject-note-${i}`).value,$(`reject-learn-${i}`).checked);

  window.loadLearning=async function(){if(!window.activeProfileId)await window.loadReviewProfiles();if(!window.activeProfileId){['lfPositive','lfBoosts','lfBad','lfPenalties'].forEach(id=>$(id).textContent='0');$('learnedRules').innerHTML='<div class="muted" style="padding:16px">Create a search profile to start learning from feedback.</div>';$('feedbackBody').innerHTML='';return}const d=await api('/api/learning?profile_id='+window.activeProfileId);$('lfPositive').textContent=d.stats.positive_events||0;$('lfBoosts').textContent=d.stats.positive_rules||0;$('lfBad').textContent=d.stats.not_suitable||0;$('lfPenalties').textContent=d.stats.negative_rules||0;$('learnedRules').innerHTML=d.rules.length?d.rules.map(r=>`<div class="learning-rule"><span class="pill ${r.polarity==='boost'?'polarity-boost':'polarity-penalty'}">${r.polarity==='boost'?'BOOST':'PENALTY'}</span><span class="pill">${esc(r.scope)}</span><span class="rule-term">${esc(r.term)}</span><span>${r.weight>0?'+':''}${r.weight}</span><span>${r.evidence_count} signals${r.strongest_event?` · ${esc(r.strongest_event)}`:''}</span><span><button class="btn small" onclick="toggleRule(${r.id},${!r.enabled})">${r.enabled?'Disable':'Enable'}</button> <button class="btn small danger" onclick="removeRule(${r.id})">Delete</button></span></div>`).join(''):'<div class="muted" style="padding:16px">No learned rules for this profile.</div>';$('feedbackBody').innerHTML=d.feedback.map(f=>`<tr><td>${esc(f.title)}<div class="muted">${esc(f.company)}</div></td><td>${esc(f.suitability)}</td><td>${esc(f.reason||'—')}</td><td>${esc((f.created_at||'').slice(0,16).replace('T',' '))}</td></tr>`).join('')};
  window.toggleRule=async(id,enabled)=>{await api(`/api/learning/rules/${id}`,{method:'PUT',body:JSON.stringify({enabled})});window.loadLearning()};window.removeRule=async id=>{if(!confirm('Delete this learned rule?'))return;await api(`/api/learning/rules/${id}`,{method:'DELETE'});window.loadLearning()};

  injectStyles();installOverview();installLearning();window.loadReviewProfiles().then(window.loadReviewJobs).catch(e=>toast(e.message,true));
})();
