(() => {
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const reasonOptions=[['wrong_role','Wrong role / function'],['german_level','German requirement too high'],['seniority','Wrong seniority'],['employment_type','Wrong employment type'],['location','Wrong location'],['company','Not interested in company'],['other','Other']];
  window.activeProfileId=window.activeProfileId||null;

  function injectStyles(){const st=document.createElement('style');st.textContent=`
    .review-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:end;margin-bottom:18px;padding:14px;background:#fff;border:1px solid var(--line);border-radius:12px}.review-toolbar .field{min-width:150px;flex:1}.review-toolbar .profile-field{min-width:220px;flex:1.35}
    .job-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:16px}.job-card{background:#fff;border:1px solid #dde3eb;border-radius:16px;padding:18px;box-shadow:0 5px 18px rgba(15,23,42,.045);display:flex;flex-direction:column;gap:14px;transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease}.job-card:hover{border-color:#c5cfdd;box-shadow:0 12px 30px rgba(15,23,42,.08);transform:translateY(-1px)}
    .job-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.job-heading{min-width:0}.job-title{display:inline-block;color:#172033;font-weight:780;font-size:17px;line-height:1.35;letter-spacing:-.012em}.job-title:hover{color:var(--accent)}.job-company{color:#526174;margin-top:6px;font-size:13px}.job-labels{display:flex;justify-content:flex-end;gap:5px;flex-wrap:wrap;flex:none}.job-labels .pill{margin:0;background:#f1f4f8;color:#475569;border:1px solid #e1e6ed}.job-labels button.pill{cursor:pointer;font:inherit;font-size:11px}
    .fit-row{display:grid;grid-template-columns:1.25fr 1fr 1fr;border:1px solid #e2e7ee;border-radius:12px;overflow:hidden;background:#f8fafc}.fit-box{position:relative;padding:11px 12px;background:transparent;border-right:1px solid #e2e7ee}.fit-box:last-child{border-right:0}.fit-box b{display:block;font-size:20px;line-height:1.1;color:#243247}.fit-box span{font-size:11px;color:var(--muted)}.fit-box:first-child b{color:var(--accent)}
    .review-actions{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:7px;margin-top:auto;padding-top:2px}.review-actions button{min-width:0}.btn.suitable{background:var(--accent);color:#fff;border-color:var(--accent)}.btn.suitable:hover{background:#1d4fc4}.btn.maybe2{background:#fff;color:#334155;border-color:#cbd5e1}.btn.unsuitable{background:#fff;color:#7f1d1d;border-color:#e1c5c2}
    .job-meta{font-size:11px;color:var(--muted);display:flex;gap:0;flex-wrap:wrap;border-top:1px solid #edf0f4;padding-top:11px}.job-meta span{display:flex;align-items:center}.job-meta span:not(:last-child)::after{content:'·';margin:0 7px;color:#a6afbc}.why-list{font-size:12px;color:#526174;display:flex;gap:6px;flex-wrap:wrap;max-height:58px;overflow:hidden}.why-list .pill{margin:0;background:#f3f5f8;color:#475569;border:1px solid transparent;border-radius:7px;padding:4px 7px}
    .job-insights{display:flex;gap:7px;flex-wrap:wrap}.job-insight{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:8px;background:#f2f6ff;color:#35507c;font-size:11px;font-weight:640}.job-insight.schedule{background:#edf8f1;color:#276744}.job-insight.language{background:#fff7e8;color:#815d18}.job-insight.fresh{background:#eaf8f5;color:#12665a}.job-insight.unknown{background:#f5f5f5;color:#64748b}.job-summary{font-size:12px;line-height:1.55;color:#536174;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.job-recommendation{font-size:11px;font-weight:720;color:#315eea}.job-language-reasons{font-size:11px;color:#68768a;line-height:1.5}.job-card.fit-priority{border-color:#c9d7ff;box-shadow:0 7px 22px rgba(49,94,234,.08)}
    .learning-rule{display:grid;grid-template-columns:90px 90px 1fr 80px 110px auto;gap:10px;align-items:center;padding:10px 12px;border-bottom:1px solid var(--line)}
    .rule-term{font-weight:700}.reject-box{display:grid;grid-template-columns:1fr;gap:8px;padding:12px;background:#fafafa;border:1px solid #e2e7ee;border-radius:10px}.reject-box textarea{min-height:54px;border:1px solid var(--line);border-radius:8px;padding:8px;resize:vertical}.reject-box select{padding:8px}.polarity-boost{background:#eef2f7;color:#334155}.polarity-penalty{background:#eef2f7;color:#334155}
    @media(max-width:700px){.review-toolbar{display:grid;padding:12px}.review-toolbar .field,.review-toolbar .profile-field{min-width:0}.job-grid{grid-template-columns:1fr}.job-card{padding:15px;gap:12px}.job-head{display:grid;gap:10px}.job-labels{justify-content:flex-start}.learning-rule{grid-template-columns:1fr 1fr}.fit-row{grid-template-columns:repeat(3,1fr)}.fit-box{padding:10px 8px}.fit-box b{font-size:18px}.review-actions{grid-template-columns:1fr}.review-actions .btn{width:100%}}
    @media(prefers-reduced-motion:reduce){.job-card{transition:none}.job-card:hover{transform:none}}`;document.head.appendChild(st)}
  function fitClass(n){return n>=75?'fit-high':n>=50?'fit-mid':'fit-low'}
  function insightMarkup(job){const reasons=job.reasons||[],language=job.language_reasons||[];const role=reasons.find(x=>x.startsWith('role family:')||x.startsWith('title:'));const schedule=job.schedule_label||reasons.find(x=>x.startsWith('schedule:'))||reasons.find(x=>x.startsWith('format:'))||reasons.find(x=>x.startsWith('employment:'));const languageReason=language.find(x=>/German|English|level/i.test(x));return [`<span class="job-insight role">◈ ${esc(job.primary_category||role?.replace(/^(?:role family|title):\s*/, '')||'Other')}</span>`,`<span class="job-insight schedule ${job.employment_type==='unknown'?'unknown':''}">◷ ${esc(job.employment_label||'Work time unknown')}${job.weekly_hours?` · ${job.weekly_hours}h/week`:''}</span>`,`<span class="job-insight fresh">◉ ${esc(job.freshness_label||'Date unknown')}</span>`,job.job_level&&job.job_level!=='Unspecified'?`<span class="job-insight role">⌁ ${esc(job.job_level)}</span>`:'',languageReason?`<span class="job-insight language">◎ ${esc(languageReason)}</span>`:''].join('')}

  function installOverview(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('jobReview'))return;const button=document.createElement('button');button.dataset.tab='jobReview';button.textContent='Job Review';nav.appendChild(button);const section=document.createElement('section');section.id='jobReview';section.className='section';section.innerHTML=`
    <div class="section-title"><div><h2>Job Review Queue</h2><div class="hint">Scores and learning are calculated independently for the selected search profile.</div></div></div>
    <div class="review-toolbar">
      <div class="field profile-field"><label>Search profile</label><select id="reviewProfile"><option>Loading…</option></select></div>
      <div class="field"><label>Decision</label><select id="reviewDecision"><option value="active">Active</option><option value="unreviewed">Unreviewed</option><option value="apply">Suitable</option><option value="maybe">Maybe</option><option value="skip">Not suitable</option><option value="all">All</option></select></div>
      <div class="field"><label>Language requirement</label><select id="reviewLanguage"><option value="preferred">Recommended</option><option value="english_first">English-first</option><option value="german_growth">German-growth</option><option value="stretch">B2 stretch</option><option value="unclear">Unclear</option><option value="all">All</option></select></div>
      <div class="field"><label>Ad language</label><select id="reviewContentLanguage"><option value="profile">Profile preference</option><option value="de">German (DE)</option><option value="en">English (EN)</option><option value="mixed">Mixed (DE/EN)</option><option value="unknown">Unknown</option><option value="all">All</option></select></div>
      <div class="field"><label>Min fit</label><input id="reviewMin" type="number" value="35" min="0" max="100"></div><button class="btn" id="reviewReload">Refresh jobs</button>
    </div><div id="jobReviewGrid" class="job-grid"></div>`;main.appendChild(section);button.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button[data-tab]').forEach(x=>x.classList.remove('active'));section.classList.add('active');button.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Job Review';window.loadReviewJobs()});
    const overview=$('overview');const oldTitle=overview?[...overview.querySelectorAll('.section-title')].find(x=>x.textContent.includes('Latest matches')):null;const oldTable=oldTitle?.nextElementSibling;if(oldTitle)oldTitle.remove();if(oldTable?.classList.contains('table-wrap'))oldTable.remove();
    ['reviewDecision','reviewLanguage','reviewContentLanguage','reviewMin'].forEach(id=>$(id).addEventListener('change',window.loadReviewJobs));$('reviewReload').addEventListener('click',window.loadReviewJobs);$('reviewProfile').addEventListener('change',()=>{window.activeProfileId=+$('reviewProfile').value;try{localStorage.setItem('jobtrack-profile',String(window.activeProfileId))}catch(e){};window.loadReviewJobs();if($('learning')?.classList.contains('active'))window.loadLearning()});
  }

  function installLearning(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('learning'))return;const b=document.createElement('button');b.dataset.tab='learning';b.textContent='Learning';nav.appendChild(b);const s=document.createElement('section');s.id='learning';s.className='section';s.innerHTML=`
    <div class="section-title"><div><h2>Profile Learning</h2><div class="hint">Boost and penalty rules belong only to the active search profile.</div></div><button class="btn" onclick="loadLearning()">Refresh</button></div>
    <div class="grid"><div class="card"><div class="muted">Positive events</div><div id="lfPositive" class="metric">—</div></div><div class="card"><div class="muted">Active boosts</div><div id="lfBoosts" class="metric">—</div></div><div class="card"><div class="muted">Not suitable</div><div id="lfBad" class="metric">—</div></div><div class="card"><div class="muted">Active penalties</div><div id="lfPenalties" class="metric">—</div></div></div>
    <div class="section-title"><h2>Learned preference rules</h2></div><div class="card" style="padding:0"><div id="learnedRules"></div></div>
    <div class="section-title"><h2>Recent review feedback</h2></div><div class="table-wrap"><table><thead><tr><th>Job</th><th>Decision</th><th>Reason</th><th>When</th></tr></thead><tbody id="feedbackBody"></tbody></table></div>`;main.appendChild(s);b.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Learning';window.loadLearning()})}

  window.loadReviewProfiles=async function(){const d=await api('/api/profiles');const sel=$('reviewProfile');if(!sel)return;let saved=null;try{saved=+localStorage.getItem('jobtrack-profile')}catch(e){};const active=d.profiles.find(p=>p.id===saved&&p.enabled)||d.profiles.find(p=>p.is_default)||d.profiles.find(p=>p.enabled)||d.profiles[0];window.activeProfileId=active?.id||null;sel.innerHTML=d.profiles.length?d.profiles.filter(p=>p.enabled).map(p=>`<option value="${p.id}" ${p.id===window.activeProfileId?'selected':''}>${esc(p.name)}${p.is_default?' · default':''}</option>`).join(''):'<option value="">Create a search profile first</option>';if(active)$('reviewMin').value=active.min_score??35;return d.profiles};

  window.loadReviewJobs=async function(){if(!window.activeProfileId)await window.loadReviewProfiles();const grid=$('jobReviewGrid');if(!grid)return;if(!window.activeProfileId){grid.innerHTML='<div class="card muted">Create a search profile to start reviewing jobs.</div>';return}const q=new URLSearchParams({limit:'150',min_score:$('reviewMin')?.value||'35',decision:$('reviewDecision')?.value||'active',language:$('reviewLanguage')?.value||'preferred',content_language:$('reviewContentLanguage')?.value||'profile',profile_id:String(window.activeProfileId)});const d=await api('/api/jobs?'+q);grid.innerHTML=d.jobs.length?d.jobs.map((j,i)=>`<article class="job-card ${j.overall_score>=75?'fit-priority':''}">
    <div class="job-head"><div class="job-heading"><a class="job-title" href="${esc(j.url)}" target="_blank" rel="noopener">${esc(j.title)}</a><div class="job-company">${esc(j.company||'Company not stated')} · ${esc(j.location||'Location not stated')}</div></div><div class="job-labels"><button class="pill" title="${Math.round((j.content_language_confidence||0)*100)}% confidence · ${esc(j.content_language_source)}; click to correct" onclick='editContentLanguage(${JSON.stringify(j.job_key)},${JSON.stringify(j.content_language)})'>${j.content_language==='de'?'DE':j.content_language==='en'?'EN':j.content_language==='mixed'?'DE/EN':'?'}</button><span class="pill">${esc((j.language_label||'unclear').replaceAll('_',' '))}</span><span class="pill" title="Provider-data completeness">Data ${j.data_quality||0}%</span></div></div>
    ${j.overall_score>=75?'<div class="job-recommendation">Strong profile match</div>':''}<div class="job-insights">${insightMarkup(j)}</div>
    ${j.description_preview?`<div class="job-summary">${esc(j.description_preview)}</div>`:''}
    <div class="fit-row"><div class="fit-box ${fitClass(j.overall_score)}"><b>${j.overall_score}</b><span>Overall fit</span></div><div class="fit-box ${fitClass(j.score)}"><b>${j.score}</b><span>Job fit</span></div><div class="fit-box ${fitClass(j.language_score)}"><b>${j.language_score}</b><span>Language fit</span></div></div>
    ${(j.language_reasons||[]).length?`<div class="job-language-reasons">${j.language_reasons.slice(0,2).map(esc).join(' · ')}</div>`:''}
    <div class="job-meta"><span>${esc(d.profile.name)}</span><span>${esc(j.source)}</span><span>Published: ${esc(j.published_date||j.created_at||'unknown')}</span>${j.postal_code?`<span>PLZ ${esc(j.postal_code)}</span>`:''}<span>Review: ${esc(j.decision||'unreviewed')}</span><span>Application: ${esc(j.application_status||'not started')}</span></div>
    <div class="why-list">${(j.reasons||[]).slice(0,10).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>
    <div class="review-actions"><button class="btn suitable" onclick='reviewJob(${JSON.stringify(j.job_key)},"suitable")'>Suitable</button><button class="btn maybe2" onclick='reviewJob(${JSON.stringify(j.job_key)},"maybe")'>Maybe</button><button class="btn unsuitable" onclick="toggleReject(${i})">Not suitable</button></div>
    <div class="reject-box" id="reject-${i}" hidden><select id="reject-reason-${i}">${reasonOptions.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><textarea id="reject-note-${i}" placeholder="Optional note"></textarea><label class="hint"><input id="reject-learn-${i}" type="checkbox" checked> Learn only for ${esc(d.profile.name)}</label><button class="btn unsuitable" onclick='submitNotSuitable(${JSON.stringify(j.job_key)},${i})'>Save as not suitable</button></div>
    </article>`).join(''):'<div class="card muted">No jobs match this profile and filters.</div>'};

  window.reviewJob=async function(jobKey,suitability,reason='',note='',learn=true){await api(`/api/jobs/${encodeURIComponent(jobKey)}/feedback`,{method:'POST',body:JSON.stringify({suitability,reason,note,learn,profile_id:window.activeProfileId})});toast(suitability==='suitable'?'Added to To Apply; preference learned for this profile':'Feedback saved');await window.loadReviewJobs();if(window.loadOverview)loadOverview()};
  window.editContentLanguage=async function(jobKey,current){if(window.APP_SHELL&&!window.APP_SHELL.isAdmin){toast('Only an administrator can change shared job-ad language metadata',true);return}const value=prompt('Ad language: de, en, mixed, unknown, or auto',current||'auto');if(value===null)return;try{await api(`/api/jobs/${encodeURIComponent(jobKey)}/content-language`,{method:'PUT',body:JSON.stringify({language:value.trim().toLowerCase()})});toast('Ad language updated');await window.loadReviewJobs()}catch(e){toast(e.message,true)}};
  window.toggleReject=i=>{const box=$(`reject-${i}`);box.hidden=!box.hidden};window.submitNotSuitable=async(jobKey,i)=>window.reviewJob(jobKey,'not_suitable',$(`reject-reason-${i}`).value,$(`reject-note-${i}`).value,$(`reject-learn-${i}`).checked);

  window.loadLearning=async function(){if(!window.activeProfileId)await window.loadReviewProfiles();if(!window.activeProfileId){['lfPositive','lfBoosts','lfBad','lfPenalties'].forEach(id=>$(id).textContent='0');$('learnedRules').innerHTML='<div class="muted" style="padding:16px">Create a search profile to start learning from feedback.</div>';$('feedbackBody').innerHTML='';return}const d=await api('/api/learning?profile_id='+window.activeProfileId);$('lfPositive').textContent=d.stats.positive_events||0;$('lfBoosts').textContent=d.stats.positive_rules||0;$('lfBad').textContent=d.stats.not_suitable||0;$('lfPenalties').textContent=d.stats.negative_rules||0;$('learnedRules').innerHTML=d.rules.length?d.rules.map(r=>`<div class="learning-rule"><span class="pill ${r.polarity==='boost'?'polarity-boost':'polarity-penalty'}">${r.polarity==='boost'?'BOOST':'PENALTY'}</span><span class="pill">${esc(r.scope)}</span><span class="rule-term">${esc(r.term)}</span><span>${r.weight>0?'+':''}${r.weight}</span><span>${r.evidence_count} signals${r.strongest_event?` · ${esc(r.strongest_event)}`:''}</span><span><button class="btn small" onclick="toggleRule(${r.id},${!r.enabled})">${r.enabled?'Disable':'Enable'}</button> <button class="btn small danger" onclick="removeRule(${r.id})">Delete</button></span></div>`).join(''):'<div class="muted" style="padding:16px">No learned rules for this profile.</div>';$('feedbackBody').innerHTML=d.feedback.map(f=>`<tr><td>${esc(f.title)}<div class="muted">${esc(f.company)}</div></td><td>${esc(f.suitability)}</td><td>${esc(f.reason||'—')}</td><td>${esc((f.created_at||'').slice(0,16).replace('T',' '))}</td></tr>`).join('')};
  window.toggleRule=async(id,enabled)=>{await api(`/api/learning/rules/${id}`,{method:'PUT',body:JSON.stringify({enabled})});window.loadLearning()};window.removeRule=async id=>{if(!confirm('Delete this learned rule?'))return;await api(`/api/learning/rules/${id}`,{method:'DELETE'});window.loadLearning()};

  injectStyles();installOverview();installLearning();window.loadReviewProfiles().then(window.loadReviewJobs).catch(e=>toast(e.message,true));
})();
