(() => {
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state={search_jobs:[],profiles:[],sources:[]};
  const st=document.createElement('style');st.textContent=`
    .sj-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px}.sj-card{border-left:4px solid #3156d3}.sj-card.off{opacity:.65;border-left-color:#a0a7b4}.sj-head{display:flex;justify-content:space-between;gap:10px}.sj-title{font-weight:800;font-size:16px}.sj-meta{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.sj-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.sj-modal{position:fixed;inset:0;background:rgba(15,23,42,.58);display:none;align-items:center;justify-content:center;z-index:120;padding:18px}.sj-modal.open{display:flex}.sj-dialog{background:#fff;border-radius:16px;width:min(980px,100%);max-height:94vh;overflow:auto;padding:22px}.sj-sources{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:7px;padding:10px;border:1px solid var(--line);border-radius:10px}.sj-keywords{min-height:112px;resize:vertical;font-family:inherit}.sj-notify{padding:12px;border:1px solid var(--line);border-radius:10px;margin-top:12px}.sj-run{font-size:12px;color:var(--muted)}
  `;document.head.appendChild(st);

  function install(){const nav=document.querySelector('.nav'),main=document.querySelector('.main');if(!nav||!main||$('searchJobs'))return;
    const b=document.createElement('button');b.dataset.tab='searchJobs';b.textContent='Search Jobs';nav.insertBefore(b,nav.querySelector('[data-tab="profiles"]')||nav.firstChild);
    const s=document.createElement('section');s.id='searchJobs';s.className='section';s.innerHTML=`<div class="section-title"><div><h2>Search Jobs</h2><div class="hint">Independent scheduled searches. Each job selects a scoring profile, sources, location, schedule and notification channels.</div></div><button class="btn primary" onclick="openSearchJob()">New search job</button></div><div id="sjGrid" class="sj-grid"></div><div class="section-title"><h2>Recent search-job runs</h2></div><div class="table-wrap"><table><thead><tr><th>Search job</th><th>Status</th><th>Fetched</th><th>Matches</th><th>Notifications</th><th>Started</th></tr></thead><tbody id="sjRuns"></tbody></table></div>`;main.appendChild(s);
    b.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Search Jobs';loadSearchJobs()});
    const m=document.createElement('div');m.id='sjModal';m.className='sj-modal';m.innerHTML=`<div class="sj-dialog"><div class="section-title" style="margin-top:0"><h2 id="sjModalTitle">Search job</h2><button class="btn" onclick="closeSearchJob()">Close</button></div><input type="hidden" id="sjId"><div class="form-grid">
      <div class="field"><label>Name</label><input id="sjName" placeholder="Werkstudent Berlin Daily"></div><div class="field"><label>Scoring profile</label><select id="sjProfile"></select></div>
      <div class="field"><label>Primary location</label><input id="sjLocation" value="Berlin"></div><div class="field"><label>Location terms</label><input id="sjLocationTerms" placeholder="berlin,potsdam,hennigsdorf"></div>
      <div class="field full"><label>Search keywords for this job</label><textarea id="sjSearchTerms" class="sj-keywords" placeholder="teilzeit process engineer&#10;part time quality engineer&#10;teilzeit produktionsplanung"></textarea><div id="sjKeywordHint" class="hint">One phrase per line or comma separated. Leave empty to inherit the selected profile.</div></div>
      <div class="field"><label>Frequency</label><select id="sjFreq"><option value="weekly">Weekly</option><option value="daily">Daily</option><option value="interval">Every N hours</option><option value="disabled">Manual only</option></select></div><div class="field"><label>Day of week</label><select id="sjDay"><option value="mon">Monday</option><option value="tue">Tuesday</option><option value="wed">Wednesday</option><option value="thu">Thursday</option><option value="fri">Friday</option><option value="sat">Saturday</option><option value="sun">Sunday</option></select></div>
      <div class="field"><label>Hour</label><input id="sjHour" type="number" min="0" max="23" value="8"></div><div class="field"><label>Minute</label><input id="sjMinute" type="number" min="0" max="59" value="0"></div>
      <div class="field"><label>Interval hours</label><input id="sjInterval" type="number" min="1" max="168" value="12"></div><div class="field"><label>Max results / notification</label><input id="sjMax" type="number" min="1" max="100" value="20"></div>
      <div class="field"><label>Min Overall Fit override</label><input id="sjMin" type="number" min="0" max="100" placeholder="inherit profile"></div><div class="field"><label>Min Language Fit override</label><input id="sjLangMin" type="number" min="0" max="100" placeholder="inherit profile"></div>
      <div class="field full"><label>Sources</label><div id="sjSources" class="sj-sources"></div><div class="hint">Select none to use every enabled automatic source.</div></div>
    </div><label><input id="sjEnabled" type="checkbox" checked> Search job enabled</label>
    <div class="sj-notify"><b>Notifications for this search job</b><div class="profile-checks"><label><input id="sjTelegram" type="checkbox"> Telegram</label><label><input id="sjEmail" type="checkbox"> Email</label></div><div class="form-grid" style="margin-top:10px">
      <div class="field"><label>Telegram Chat ID override</label><input id="sjChat" placeholder="blank = global"></div><div class="field"><label>Telegram Bot Token override</label><input id="sjToken" type="password" placeholder="blank = global"></div>
      <div class="field"><label>Email recipient override</label><input id="sjEmailTo" placeholder="blank = global"></div><div class="field"><label>Email sender override</label><input id="sjEmailFrom" placeholder="blank = global"></div>
      <div class="field"><label>SMTP host override</label><input id="sjSmtpHost" placeholder="blank = global"></div><div class="field"><label>SMTP port</label><input id="sjSmtpPort" type="number" placeholder="587"></div>
      <div class="field"><label>SMTP username override</label><input id="sjSmtpUser" placeholder="blank = global"></div><div class="field"><label>SMTP password override</label><input id="sjSmtpPass" type="password" placeholder="blank = global"></div>
    </div></div><div class="actions"><button class="btn primary" onclick="saveSearchJob()">Save search job</button><span id="sjStatus" class="status"></span></div></div>`;document.body.appendChild(m);
  }

  function fmtSchedule(j){if(!j.enabled)return'Disabled';if(j.frequency==='interval')return`Every ${j.interval_hours}h`;if(j.frequency==='daily')return`Daily ${String(j.hour).padStart(2,'0')}:${String(j.minute).padStart(2,'0')}`;if(j.frequency==='disabled')return'Manual only';return`${(j.day_of_week||'mon').toUpperCase()} ${String(j.hour).padStart(2,'0')}:${String(j.minute).padStart(2,'0')}`}
  function keywordLabel(j){if(j.search_terms?.length)return`${j.search_terms.length} own keywords`;const p=state.profiles.find(x=>x.id===j.profile_id),n=Object.keys(p?.keywords?.search||{}).length;return`${n} inherited keywords`}
  function updateKeywordHint(){const p=state.profiles.find(x=>x.id===+$('sjProfile').value),terms=Object.keys(p?.keywords?.search||{});$('sjKeywordHint').textContent=terms.length?`Leave empty to inherit ${terms.length} keywords from “${p.name}”, including: ${terms.slice(0,3).join(', ')}${terms.length>3?'…':''}`:'This profile has no fallback search keywords. Add at least one phrase.'}
  window.loadSearchJobs=async function(){const d=await api('/api/search-jobs');state=d;const g=$('sjGrid');if(g)g.innerHTML=d.search_jobs.map(j=>`<div class="card sj-card ${j.enabled?'':'off'}"><div class="sj-head"><div><div class="sj-title">${esc(j.name)}</div><div class="muted">${esc(j.profile_name)} · ${esc(j.target_location)}</div></div><span class="pill">${j.enabled?'ACTIVE':'OFF'}</span></div><div class="sj-meta"><span class="pill">${esc(fmtSchedule(j))}</span><span class="pill">${esc(keywordLabel(j))}</span><span class="pill">${j.source_ids.length?j.source_ids.length+' sources':'all sources'}</span>${j.notify_telegram?'<span class="pill">Telegram</span>':''}${j.notify_email?'<span class="pill">Email</span>':''}</div><div class="sj-run">Last: ${esc(j.last_run_status||'never')} · ${j.last_match_count||0} matches<br>Next: ${esc(j.next_run||'—')}</div><div class="sj-actions"><button class="btn" onclick="runSearchJob(${j.id})">Run now</button><button class="btn" onclick="openSearchJob(${j.id})">Edit</button><button class="btn danger" onclick="removeSearchJob(${j.id})">Delete</button></div></div>`).join('')||'<div class="card muted">No search jobs yet.</div>';loadSearchJobRuns();return d};
  async function loadSearchJobRuns(){const d=await api('/api/search-job-runs');const b=$('sjRuns');if(b)b.innerHTML=d.runs.map(r=>`<tr><td>${esc(r.search_job_name)}</td><td>${esc(r.status)}</td><td>${r.fetched}</td><td>${r.matches}</td><td>${esc((r.notification_channels||[]).join(', ')||'—')}</td><td>${esc((r.started_at||'').slice(0,16).replace('T',' '))}</td></tr>`).join('')}
  window.openSearchJob=function(id){const j=id?state.search_jobs.find(x=>x.id===id):null;$('sjId').value=j?.id||'';$('sjModalTitle').textContent=j?'Edit search job':'New search job';$('sjName').value=j?.name||'';$('sjProfile').innerHTML=state.profiles.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('sjProfile').value=j?.profile_id||state.profiles[0]?.id||'';$('sjProfile').onchange=updateKeywordHint;$('sjSearchTerms').value=(j?.search_terms||[]).join('\n');updateKeywordHint();$('sjLocation').value=j?.target_location||'Berlin';$('sjLocationTerms').value=(j?.location_terms||[]).join(',');$('sjFreq').value=j?.frequency||'weekly';$('sjDay').value=j?.day_of_week||'mon';$('sjHour').value=j?.hour??8;$('sjMinute').value=j?.minute??0;$('sjInterval').value=j?.interval_hours??12;$('sjMax').value=j?.max_results??20;$('sjMin').value=j?.min_score_override??'';$('sjLangMin').value=j?.min_language_score_override??'';$('sjEnabled').checked=j?.enabled??true;$('sjTelegram').checked=j?.notify_telegram??false;$('sjEmail').checked=j?.notify_email??false;const n=j?.notification||{};$('sjChat').value=n.telegram_chat_id||'';$('sjEmailTo').value=n.email_to||'';$('sjEmailFrom').value=n.email_from||'';$('sjSmtpHost').value=n.smtp_host||'';$('sjSmtpPort').value=n.smtp_port||'';$('sjSmtpUser').value=n.smtp_username||'';$('sjToken').value='';$('sjSmtpPass').value='';$('sjSources').innerHTML=state.sources.map(s=>`<label><input type="checkbox" class="sj-source" value="${s.id}" ${(j?.source_ids||[]).includes(s.id)?'checked':''}> ${esc(s.name)} <span class="muted">${esc(s.source_type)}</span></label>`).join('');$('sjModal').classList.add('open')};
  window.closeSearchJob=()=>$('sjModal').classList.remove('open');
  window.saveSearchJob=async function(){const id=+$('sjId').value;const nullable=id=>$(id).value===''?null:+$(id).value;const payload={name:$('sjName').value.trim(),enabled:$('sjEnabled').checked,profile_id:+$('sjProfile').value,target_location:$('sjLocation').value.trim()||'Berlin',location_terms:$('sjLocationTerms').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),search_terms:$('sjSearchTerms').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean),source_ids:[...document.querySelectorAll('.sj-source:checked')].map(x=>+x.value),frequency:$('sjFreq').value,day_of_week:$('sjDay').value,hour:+$('sjHour').value||0,minute:+$('sjMinute').value||0,interval_hours:+$('sjInterval').value||12,min_score_override:nullable('sjMin'),min_language_score_override:nullable('sjLangMin'),max_results:+$('sjMax').value||20,notify_telegram:$('sjTelegram').checked,notify_email:$('sjEmail').checked,notification:{telegram_chat_id:$('sjChat').value.trim(),email_to:$('sjEmailTo').value.trim(),email_from:$('sjEmailFrom').value.trim(),smtp_host:$('sjSmtpHost').value.trim(),smtp_port:$('sjSmtpPort').value?+$('sjSmtpPort').value:'',smtp_username:$('sjSmtpUser').value.trim()},secrets:{telegram_bot_token:$('sjToken').value,smtp_password:$('sjSmtpPass').value}};try{await api(id?`/api/search-jobs/${id}`:'/api/search-jobs',{method:id?'PUT':'POST',body:JSON.stringify(payload)});toast('Search job saved');closeSearchJob();await loadSearchJobs()}catch(e){$('sjStatus').textContent=e.message;$('sjStatus').className='status error'}};
  window.runSearchJob=async id=>{toast('Search started');try{const d=await api(`/api/search-jobs/${id}/run`,{method:'POST'});toast(`${d.matches} matches found`);await loadSearchJobs()}catch(e){toast(e.message,true)}};
  window.removeSearchJob=async id=>{if(!confirm('Delete this search job and its run history?'))return;await api(`/api/search-jobs/${id}`,{method:'DELETE'});toast('Search job deleted');await loadSearchJobs()};
  install();loadSearchJobs().catch(()=>{});
})();
