"""Shared bilingual role intent for provider queries and vacancy matching."""

from .text_match import contains_affirmed_phrase, normalize_text


ROLE_FAMILIES: dict[str, tuple[str, ...]] = {
    "quality": (
        "quality engineer",
        "supplier quality engineer",
        "customer quality engineer",
        "plant quality engineer",
        "production quality engineer",
        "quality assurance engineer",
        "quality planning engineer",
        "apqp engineer",
        "quality manager",
        "quality specialist",
        "quality assurance",
        "quality control",
        "quality inspection",
        "quality inspector",
        "quality technician",
        "qualitätsingenieur",
        "qualitaetsingenieur",
        "supplier quality",
        "qualitätsmanager",
        "qualitaetsmanager",
        "qualitätsspezialist",
        "qualitaetsspezialist",
        "qualitätsplanung",
        "qualitaetsplanung",
        "qualitätsplaner",
        "qualitaetsplaner",
        "lieferantenqualitätsingenieur",
        "lieferantenqualitaetsingenieur",
        "kundenqualitätsingenieur",
        "kundenqualitaetsingenieur",
        "qualitätssicherung",
        "qualitaetssicherung",
        "qualitätskontrolle",
        "qualitaetskontrolle",
        "qualitätsprüfung",
        "qualitaetspruefung",
        "qualitätsprüfer",
        "qualitaetspruefer",
        "wareneingangsprüfung",
    ),
    "production": (
        "production engineer",
        "manufacturing engineer",
        "industrial engineer",
        "production manager",
        "production coordinator",
        "production technician",
        "manufacturing specialist",
        "produktionsingenieur",
        "produktionsmanager",
        "produktionskoordinator",
        "produktionstechniker",
        "fertigungsingenieur",
        "fertigungsleiter",
        "fertigungskoordinator",
        "manufacturing engineering",
    ),
    "planning": (
        "production planner",
        "production planning",
        "production scheduling",
        "manufacturing planner",
        "production scheduler",
        "material planning",
        "produktionsplanung",
        "produktionsplaner",
        "fertigungsplanung",
        "fertigungsplaner",
        "fertigungssteuerung",
        "fertigungssteuerer",
        "arbeitsvorbereitung",
        "arbeitsvorbereiter",
    ),
    "process": (
        "process engineer",
        "process engineering",
        "manufacturing process engineer",
        "production process engineer",
        "process development engineer",
        "process improvement engineer",
        "process specialist",
        "industrialization engineer",
        "industrialisation engineer",
        "process optimization",
        "continuous improvement",
        "operational excellence",
        "lean engineer",
        "prozessingenieur",
        "prozessentwickler",
        "prozessentwicklungsingenieur",
        "prozessoptimierungsingenieur",
        "prozesstechniker",
        "prozessoptimierung",
        "prozessplanung",
        "prozesstechnik",
        "verfahrenstechniker",
        "industrialisierungsingenieur",
        "fertigungsprozessingenieur",
    ),
    "coating": (
        "coating engineer",
        "paint engineer",
        "painting engineer",
        "paint shop engineer",
        "paint process engineer",
        "paint quality engineer",
        "coating process engineer",
        "surface treatment engineer",
        "surface technology engineer",
        "coating specialist",
        "lackieringenieur",
        "lackierprozessingenieur",
        "lackiertechniker",
        "lackierspezialist",
        "lackierplaner",
        "lackierprozess",
        "beschichtungsingenieur",
        "beschichtungstechniker",
        "beschichtungstechnik",
        "oberflächentechnik",
        "oberflaechentechnik",
        "oberflächenbehandlung",
        "oberflaechenbehandlung",
        "oberflächeningenieur",
        "oberflaecheningenieur",
    ),
    "technical office": (
        "technical office",
        "technical specialist",
        "technical assistant",
        "technical documentation",
        "office assistant",
        "administrative assistant",
        "project assistant",
        "technische sachbearbeitung",
        "sachbearbeitung",
        "projektassistenz",
        "dokumentation",
        "büroassistenz",
        "bueroassistenz",
    ),
    "procurement": (
        "procurement",
        "procurement specialist",
        "purchasing",
        "buyer",
        "purchasing assistant",
        "einkauf",
        "einkäufer",
        "einkaeufer",
    ),
    "logistics": (
        "supply chain",
        "logistics",
        "logistics coordinator",
        "logistik",
        "lieferkette",
        "supply chain assistant",
    ),
}


# Provider queries deliberately use a small, high-signal vocabulary. The complete
# aliases above are for matching; sending all of them to a job board would consume
# query budgets without improving coverage.
ROLE_QUERY_TERMS: dict[str, tuple[str, str]] = {
    "quality": ("quality engineer", "qualitätsingenieur"),
    "production": ("manufacturing engineer", "produktionsingenieur"),
    "planning": ("production planner", "produktionsplaner"),
    "process": ("process engineer", "prozessingenieur"),
    "coating": ("coating engineer", "lackieringenieur"),
    "technical office": ("technical specialist", "technische sachbearbeitung"),
    "procurement": ("procurement specialist", "einkauf spezialist"),
    "logistics": ("supply chain specialist", "supply chain spezialist"),
}


PROFESSIONAL_TITLE_SIGNALS = (
    "engineer",
    "ingenieur",
    "specialist",
    "spezialist",
    "manager",
    "technician",
    "techniker",
    "planner",
    "planer",
    "coordinator",
    "koordinator",
    "technologist",
    "technologe",
    "arbeitsvorbereiter",
)


CONFLICTING_TITLE_SIGNALS = (
    "software",
    "android",
    "ios developer",
    "frontend",
    "backend",
    "full stack",
    "full-stack",
    "devops",
    "cloud",
    "data engineer",
    "machine learning",
    "cyber security",
    "cybersecurity",
    "test automation",
    "qa automation",
)


INDUSTRIAL_DOMAIN_SIGNALS = (
    "automotive",
    "manufacturing",
    "production process",
    "production line",
    "factory",
    "plant",
    "shop floor",
    "supplier quality",
    "iatf 16949",
    "iso 9001",
    "fmea",
    "pfmea",
    "spc",
    "8d",
    "root cause",
    "lean manufacturing",
    "six sigma",
    "yield",
    "cycle time",
    "coating",
    "paint process",
    "lackierprozess",
    "beschichtung",
    "fertigung",
    "produktion",
)


def role_families_for_terms(terms) -> list[str]:
    """Return only families explicitly requested by this profile."""
    requested = [normalize_text(str(term)) for term in terms if normalize_text(str(term))]
    return [
        family
        for family, aliases in ROLE_FAMILIES.items()
        if any(contains_affirmed_phrase(term, alias) for term in requested for alias in aliases)
    ]


def matched_role_families(text: str, requested_families: list[str]) -> list[str]:
    return [
        family
        for family in requested_families
        if any(contains_affirmed_phrase(text, alias) for alias in ROLE_FAMILIES.get(family, ()))
    ]
